include: package:lint/analysis_options.yaml

analyzer:
  errors:
    unused_local_variable: ignore
  exclude: [lib/data/network/entity/*.g.dart, lib/util/l10n/**]

linter:
  rules:
    file_names: false
